version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: weather-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=weather_data
    volumes:
      - mongodb_data:/data/db
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local